# Random Forest Classification with gridsearch

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('labeled_dysx.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[0.4 0.6 0.4 0.7 0.7 0.7]
 [0.5 0.7 0.8 0.9 0.8 0.7]
 [0.7 1.  0.7 0.8 0.7 0.9]
 ...
 [0.7 0.4 0.4 0.5 0.4 0.4]
 [0.8 0.7 0.8 0.6 0.7 0.9]
 [0.7 0.6 0.8 0.8 0.9 0.7]]


In [5]:
print(y_train)

[1 1 2 2 0 1 2 2 2 2 0 1 1 2 1 2 1 2 1 1 2 1 1 1 0 2 1 0 1 1 2 0 1 0 1 1 2
 2 0 1 2 2 0 2 1 2 2 2 2 1 1 2 1 1 1 1 2 1 1 2 2 1 1 2 2 0 1 1 0 0 1 1 1 2
 1 0 1 2 2 0 1 0 1 1 1 1 1 2 1 1 1 0 1 2 1 1 1 2 1 1 1 1 1 1 1 2 0 2 0 1 1
 0 2 1 1 1 1 0 2 1 2 1 1 2 1 2 0 0 1 0 0 1 2 1 1 1 1 1 2 1 1 0 1 2 1 2 2 1
 1 1 2 2 2 2 0 1 1 0 2 1 0 1 2 1 2 2 2 1 1 2 1 1 1 0 0 1 1 1 1 1 2 1 2 1 1
 0 0 1 2 0 2 2 1 1 1 1 0 1 0 0 0 0 1 1 1 2 2 1 0 1 1 1 1 1 0 2 0 2 2 1 1 2
 2 0 1 1 2 1 2 1 0 1 1 1 2 1 1 1 1 1 1 2 2 2 2 1 2 1 1 2 1 1 1 1 2 1 1 1 1
 2 1 2 1 2 2 0 2 2 0 1 1 2 2 2 1 2 2 0 1 1 2 1 2 2 2 1 2 1 2 2 1 1 1 1 1 1
 1 0 2 2 1 2 2 2 1 2 0 0 0 1 1 2 1 2 1 1 1 1 1 1 2 0 2 1 1 2 2 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 2 2 1 2 1 1 1 1 1 0 1 2 2 2 1 2 0 0 2 2 1 2 2 2 1 1 2 1 2
 2 0 1 2 2]


In [6]:
print(X_test)

[[0.5 0.5 0.5 0.7 0.4 0.4]
 [0.5 0.5 0.6 0.4 0.5 0.6]
 [0.5 0.8 0.6 0.8 0.9 0.8]
 [0.3 0.3 0.3 0.4 0.3 0. ]
 [0.8 0.9 0.5 0.8 0.8 1. ]
 [0.6 0.5 0.5 0.5 0.4 0.4]
 [0.3 0.3 0.7 0.4 0.5 0.5]
 [1.  0.6 0.6 0.7 0.7 0.8]
 [0.2 0.  0.1 0.  0.3 0.5]
 [0.5 0.6 0.4 0.6 0.3 0.6]
 [0.5 0.3 0.5 0.5 0.4 0.1]
 [0.8 0.7 0.6 0.6 0.6 0.7]
 [0.5 0.3 0.5 0.2 0.3 0.2]
 [0.5 0.8 0.8 0.8 0.6 0.9]
 [0.4 0.3 0.2 0.1 0.  0.5]
 [0.6 0.6 0.6 1.  0.6 0.8]
 [0.7 0.6 0.8 0.9 0.7 0.5]
 [0.6 0.3 0.5 0.4 0.6 0.4]
 [0.6 0.6 0.6 0.3 0.5 0.6]
 [0.5 0.3 0.4 0.6 0.7 0.6]
 [0.8 0.8 0.7 0.7 0.8 0.7]
 [0.3 0.7 0.5 0.5 0.5 0.4]
 [0.5 0.7 0.6 0.7 0.5 0.3]
 [0.6 0.6 0.9 0.7 0.9 0.5]
 [0.7 0.6 0.7 0.5 0.6 0.8]
 [0.7 0.5 0.8 0.6 0.6 0.8]
 [0.7 0.6 0.6 0.9 0.7 0.7]
 [0.5 0.8 0.6 0.7 0.8 0.8]
 [0.6 0.7 0.6 0.6 0.6 0.7]
 [0.7 0.8 0.5 0.7 0.5 0.8]
 [0.5 0.5 0.4 0.7 0.3 0.6]
 [0.6 0.7 0.4 0.4 0.7 0.3]
 [0.7 0.7 0.6 0.9 0.6 1. ]
 [0.5 0.8 0.5 0.6 0.8 0.5]
 [0.5 0.5 0.5 0.5 0.4 0.4]
 [0.8 0.9 1.  0.6 0.8 0.6]
 [0.7 0.5 0.7 1.  0.6 0.7]
 

In [7]:
print(y_test)

[1 1 1 0 2 1 1 2 0 1 1 2 1 1 0 1 2 1 1 1 2 1 1 1 1 1 2 1 1 2 1 1 2 1 1 2 1
 1 2 2 1 2 1 1 1 2 1 2 1 2 2 1 2 1 2 2 2 1 1 1 1 1 1 2 1 2 1 1 2 2 1 1 1 1
 1 1 2 2 2 1 1 2 2 0 1 2 1 1 2 1 1 1 1 1 1 1 0 2 1 0 1 1 1 1 2 2 1 1 2 2 2
 1 1 1 1 1 1 1 1 2 2 2 0 1 2]


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[-0.82998771  0.15372824 -0.75292749  0.57509917  0.62113512  0.60081378]
 [-0.34593578  0.60765022  1.03408396  1.49673245  1.11357839  0.60081378]
 [ 0.62216808  1.96941616  0.5873311   1.03591581  0.62113512  1.54747414]
 ...
 [ 0.62216808 -0.75411572 -0.75292749 -0.34653411 -0.85619471 -0.81917677]
 [ 1.10622001  0.60765022  1.03408396  0.11428253  0.62113512  1.54747414]
 [ 0.62216808  0.15372824  1.03408396  1.03591581  1.60602167  0.60081378]]


In [10]:
print(X_test)

[[-0.34593578 -0.30019374 -0.30617463  0.57509917 -0.85619471 -0.81917677]
 [-0.34593578 -0.30019374  0.14057823 -0.80735075 -0.36375143  0.1274836 ]
 [-0.34593578  1.0615722   0.14057823  1.03591581  1.60602167  1.07414396]
 [-1.31403964 -1.2080377  -1.19968036 -0.80735075 -1.34863798 -2.7124975 ]
 [ 1.10622001  1.51549418 -0.30617463  1.03591581  1.11357839  2.02080432]
 [ 0.13811615 -0.30019374 -0.30617463 -0.34653411 -0.85619471 -0.81917677]
 [-1.31403964 -1.2080377   0.5873311  -0.80735075 -0.36375143 -0.34584659]
 [ 2.07432387  0.15372824  0.14057823  0.57509917  0.62113512  1.07414396]
 [-1.79809157 -2.56980363 -2.09318608 -2.65061732 -1.34863798 -0.34584659]
 [-0.34593578  0.15372824 -0.75292749  0.11428253 -1.34863798  0.1274836 ]
 [-0.34593578 -1.2080377  -0.30617463 -0.34653411 -0.85619471 -2.23916731]
 [ 1.10622001  0.60765022  0.14057823  0.11428253  0.12869184  0.60081378]
 [-0.34593578 -1.2080377  -0.30617463 -1.72898404 -1.34863798 -1.76583713]
 [-0.34593578  1.0615722 

## Training the Random Forest Classification model on the Training set

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
n_est = {'n_estimators' : [10,100,500,1000]}
rf_grid = GridSearchCV(RandomForestClassifier(random_state=0),n_est,scoring='f1_macro')
rf_grid.fit(X_train, y_train)
pred_rf_grid = rf_grid.predict(X_test)
print('Best value of n_estimator for RandomForest model is:',rf_grid.best_params_)
y_pred_ = rf_grid.predict(X_test)

Best value of n_estimator for RandomForest model is: {'n_estimators': 1000}


##Input from user


In [12]:
import joblib
joblib.dump(rf_grid,'model_joblib')
joblib.dump(sc,'sc_model')

['sc_model']

In [13]:
#Calculations of Scores -
Language_vocab = (4+4+4+0+4+4+4)/28
Memory = (4 + 0)/8
#Speed = Calculated on the basis of time taken to complete the quiz(for now lets take some value)
speed = float(input("Enter speed: "))
Visual_discrimination = (4+0+4+0)/16
Audio_Discrimination = (0+4)/8
Survey_Score = (4+0+4+4+0+4+4+0+4+0+4+0+4+4+4+0+0+4+0+4)/80
a=[Language_vocab,Memory,speed,Visual_discrimination,Audio_Discrimination,Survey_Score]

In [14]:
print(rf_grid.predict(sc.transform([[1, 0, 0.9, 1, 1, 0]])))

[1]


## Predicting the Test set results

In [15]:
y_pred = rf_grid.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 0]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [2 2]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [2 2]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [1 1]
 [2 2]]


## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  1  0]
 [ 3 71  3]
 [ 0  3 38]]


0.92